#!/bin/bash

sudo apt-get --assume-yes update

wait

sudo apt-get --assume-yes install \
    linux-image-extra-$(uname -r) \
    linux-image-extra-virtual

wait

sudo apt-get --assume-yes install \
    apt-transport-https \
    ca-certificates \
    curl \
    software-properties-common

wait

curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -

wait

sudo add-apt-repository \
   "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
   $(lsb_release -cs) \
   stable"

wait

sudo apt-get --assume-yes update

wait

sudo apt-get --assume-yes install docker-ce

wait

sudo docker run hello-world
