#!/bin/bash

sudo apt-get --assume-yes update

wait

sudo apt-get --assume-yes install \
    linux-image-extra-$(uname -r) \
    linux-image-extra-virtual

wait

sudo apt-get --assume-yes install \
    apt-transport-https \
    ca-certificates \
    curl \
    software-properties-common

wait

curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -

wait

sudo add-apt-repository \
   "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
   $(lsb_release -cs) \
   stable"

wait

sudo apt-get --assume-yes update

wait

sudo apt-get --assume-yes install docker-ce

wait

sudo docker run hello-world

wait

git clone https://github.com/DinoTools/dionaea-docker.git

wait

cd dionaea-docker/0.5

wait

docker build -t my-dionaea .

wait

cd ..

wait

git clone https://github.com/mushorg/glastopf.git

wait

cd glastopf

wait

docker build --rm --tag glastopf .

wait

cd ..


wait

sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 0C49F3730359A14518585931BC711F9BA15703C6

wait

echo "deb [ arch=amd64,arm64 ] http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.4 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-3.4.list

wait

sudo apt-get --assume-yes update

wait

sudo apt-get --assume-yes install -y mongodb-org

wait

sudo service mongod start

wait

echo use glastopf > glastopf.js

wait

mongo < glastopf.js

wait

echo use dionaea > dionaea.js

wait

mongo < dionaea.js

echo "Now run the startpots script!!!!!!!!!!!!!!!!!!"
